<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DataContexts\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BlogPostAPIProsigliere.Domain\BlogPostAPIProsigliere.Domain\BlogPostAPIProsigliere.Domain.csproj" />
  </ItemGroup>

</Project>
